local opt = vim.opt

opt.backup = false
-- opt.clipboard = "unnamedplus"
opt.cmdheight = 2
opt.completeopt = { "menuone", "noselect" }
opt.conceallevel = 0
opt.fileencoding = "utf-8"
opt.hlsearch = true
opt.ignorecase = true
-- opt.mouse = "a" -- allows mouse to be used
opt.pumheight = 10 -- popup menu height
opt.showmode = false
opt.showtabline = 2
opt.tabstop = 2
opt.softtabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.smartcase = true
opt.smartindent = true
opt.autoindent = true
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false -- disables swapfiles
-- opt.termguicolors = true -- terminal gui colors
-- opt.timeoutlen = 1000
opt.undofile = true
opt.updatetime = 300 -- faster completion (4000ms default)
opt.writebackup = false
opt.cursorline = true -- this sounds like it could be ugly
opt.number = true -- numbered lines
opt.relativenumber = true -- relative number lines
opt.numberwidth = 4 -- number column width (default 4)
opt.signcolumn = "auto" -- the gray column on the left
opt.wrap = false -- word wrap
opt.scrolloff = 8
